### ISSUE TITLE
[4.0] [Meta] Frontend Übersetzungen

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/joomla#701]
## Beschreibung

Das hier ist ein Meta Issue für die Frontend Übersetzungen. Bitte alle Dateien anhaken wofür die Übersetzungen geprüft wurden oder PRs erstellt wurden.

## Dateien

- [x] de-DE.com_ajax.ini
- [x] de-DE.com_config.ini
- [x] de-DE.com_contact.ini
- [x] de-DE.com_content.ini
- [X] de-DE.com_finder.commonwords.txt (neue Datei)
- [x] de-DE.com_finder.ini
- [x] de-DE.com_mailto.ini
- [x] de-DE.com_media.ini
- [x] de-DE.com_messages.ini
- [x] de-DE.com_newsfeeds.ini
- [x] de-DE.com_privacy.ini
- [x] de-DE.com_search.ini
- [x] de-DE.com_tags.ini
- [x] de-DE.com_users.ini
- [X] de-DE.com_weblinks.ini (gelöscht)
- [x] de-DE.com_wrapper.ini
- [x] de-DE.files_joomla.sys.ini
- [x] de-DE.finder_cli.ini
- [x] de-DE.ini
- [X] de-DE.lib_fof.ini (gelöscht)
- [X] de-DE.lib_fof.sys.ini (gelöscht)
- [X] de-DE.lib_idna_convert.sys.ini (gelöscht)
- [x] de-DE.lib_joomla.ini
- [x] de-DE.lib_joomla.sys.ini
- [x] de-DE.lib_phpass.sys.ini
- [X] de-DE.lib_phputf8.sys.ini (gelöscht)
- [x] de-DE.lib_simplepie.sys.ini
- [x] de-DE.localise.php
- [x] de-DE.mod_articles_archive.ini
- [x] de-DE.mod_articles_archive.sys.ini
- [x] de-DE.mod_articles_categories.ini
- [x] de-DE.mod_articles_categories.sys.ini
- [x] de-DE.mod_articles_category.ini
- [x] de-DE.mod_articles_category.sys.ini
- [x] de-DE.mod_articles_latest.ini
- [x] de-DE.mod_articles_latest.sys.ini
- [x] de-DE.mod_articles_news.ini
- [x] de-DE.mod_articles_news.sys.ini
- [x] de-DE.mod_articles_popular.ini
- [x] de-DE.mod_articles_popular.sys.ini
- [x] de-DE.mod_banners.ini
- [x] de-DE.mod_banners.sys.ini
- [x] de-DE.mod_breadcrumbs.ini
- [x] de-DE.mod_breadcrumbs.sys.ini
- [x] de-DE.mod_custom.ini
- [x] de-DE.mod_custom.sys.ini
- [x] de-DE.mod_feed.ini
- [x] de-DE.mod_feed.sys.ini
- [x] de-DE.mod_finder.ini
- [x] de-DE.mod_finder.sys.ini
- [x] de-DE.mod_footer.ini
- [x] de-DE.mod_footer.sys.ini
- [x] de-DE.mod_languages.ini
- [x] de-DE.mod_languages.sys.ini
- [x] de-DE.mod_login.ini
- [x] de-DE.mod_login.sys.ini
- [x] de-DE.mod_menu.ini
- [x] de-DE.mod_menu.sys.ini
- [x] de-DE.mod_random_image.ini
- [x] de-DE.mod_random_image.sys.ini
- [x] de-DE.mod_related_items.ini
- [x] de-DE.mod_related_items.sys.ini
- [x] de-DE.mod_search.ini
- [x] de-DE.mod_search.sys.ini
- [x] de-DE.mod_stats.ini
- [x] de-DE.mod_stats.sys.ini
- [x] de-DE.mod_syndicate.ini
- [x] de-DE.mod_syndicate.sys.ini
- [x] de-DE.mod_tags_popular.ini
- [x] de-DE.mod_tags_popular.sys.ini
- [x] de-DE.mod_tags_similar.ini
- [x] de-DE.mod_tags_similar.sys.ini
- [x] de-DE.mod_users_latest.ini
- [x] de-DE.mod_users_latest.sys.ini
- [X] de-DE.mod_weblinks.ini (gelöscht)
- [X] de-DE.mod_weblinks.sys.ini (gelöscht)
- [x] de-DE.mod_whosonline.ini
- [x] de-DE.mod_whosonline.sys.ini
- [x] de-DE.mod_wrapper.ini
- [x] de-DE.mod_wrapper.sys.ini
- [x] de-DE.tpl_cassiopeia.ini  (neue Datei)
- [x] de-DE.tpl_cassiopeia.sys.ini  (neue Datei)
- [X] de-DE.tpl_beez3.ini (gelöscht)
- [X] de-DE.tpl_beez3.sys.ini (gelöscht)
- [X] de-DE.tpl_protostar.ini (gelöscht)
- [X] de-DE.tpl_protostar.sys.ini (gelöscht)
- [X] de-DE.xml (wird beim Release automatisch angepasst)
- [X] install.xml (wird beim Release automatisch angepasst)

**Comment by zero-24** [comment]
Die Dateien welche gelöscht werden müssen + de-DE.com_finder.commonwords.txt: https://github.com/joomlagerman/joomla/pull/702

**Comment by zero-24** [comment]
- de-DE.com_ajax.ini
- de-DE.com_config.ini
- de-DE.com_contact.ini
- de-DE.com_content.ini

=> https://github.com/joomlagerman/joomla/pull/703

**Comment by zero-24** [comment]
- de-DE.com_finder.ini
- de-DE.com_mailto.ini
- de-DE.com_messages.ini
- de-DE.com_newsfeeds.ini
- de-DE.com_search.ini
- de-DE.com_tags.ini

=> https://github.com/joomlagerman/joomla/pull/704

**Comment by zero-24** [comment]
- de-DE.mod_articles_*

=> https://github.com/joomlagerman/joomla/pull/705

**Comment by zero-24** [comment]
- de-DE.mod_banners.ini
- de-DE.mod_banners.sys.ini
- de-DE.mod_breadcrumbs.ini
- de-DE.mod_breadcrumbs.sys.ini
- de-DE.mod_custom.ini
- de-DE.mod_custom.sys.ini
- de-DE.mod_feed.ini
- de-DE.mod_feed.sys.ini

https://github.com/joomlagerman/joomla/pull/706

**Comment by zero-24** [comment]
- de-DE.mod_finder.ini
- de-DE.mod_languages.ini
- de-DE.mod_login.ini
- de-DE.mod_menu.ini
- de-DE.mod_random_image.ini
- de-DE.mod_search.ini
- de-DE.mod_stats.ini
- de-DE.mod_syndicate.ini

=> https://github.com/joomlagerman/joomla/pull/707

**Comment by zero-24** [comment]
- de-DE.mod_tags_popular.ini
- de-DE.mod_tags_similar.ini
- de-DE.mod_users_latest.ini
- de-DE.mod_wrapper.ini

=> https://github.com/joomlagerman/joomla/pull/708

**Comment by tecpromotion** [comment]
nothing changed in de-DE.com_privacy.ini yet

**Comment by zero-24** [comment]
https://github.com/joomlagerman/joomla/pull/717

**Comment by zero-24** [comment]
https://github.com/joomlagerman/joomla/pull/718 - de-DE.mod_articles_category.ini

**Comment by zero-24** [comment]
Closing da alle Frontend Dateien eine PR haben bzw. + überprüft wurden.
